<a href="https://colab.research.google.com/github/EngRenan/Data-Analysis---Exploratory/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [61]:
#Carregando o dataframe
df = pd.read_excel('/content/ZRPP019 (1) (1).xlsx')

In [62]:
df.head(25)

,Ordem,Tipo de ordem first,Tipo de ordem,Operação,Centro de trabalho,Texto breve material,Nº peça fabricante,Quantidade operação,Fim real operação
0,1792311,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
1,1792311,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
2,1792311,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
3,1792312,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
4,1792312,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
5,1792312,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
6,1792313,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
7,1792313,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
8,1792313,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
9,1904892,ZSER,ZSER,60,3508,-,NaN,8,2022-05-13
10,1920777,ZSER,ZSER,70,3508,-,NaN,1,2022-08-17
11,1925389,ZSER,ZSER,70,3508,-,NaN,1,2022-09-19
12,1934730,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
13,1934731,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
14,1934733,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
15,1934734,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
16,1939467,ZSER,ZSER,60,3508,-,NaN,12,2023-02-13
17,1910685,ZRET,ZRET,20,3650,007907269 / 400054806 / MICROESFERAVIDRO,NaN,1,2022-05-30
18,1910686,ZRET,ZRET,20,3650,007907269 / 400054807 / MICROESFERAVIDRO,NaN,1,2022-05-30
19,1910687,ZRET,ZRET,20,3650,007907269 / 400054808 / MICROESFERAVIDRO,NaN,1,2022-05-30
20,1912785,ZRET,ZRET,20,3650,007907269 / 400055003 / MICROESFERAVIDRO,NaN,1,2022-06-15
21,1912786,ZRET,ZRET,20,3650,007907269 / 400055004 / MICROESFERAVIDRO,NaN,1,2022-06-15
22,1917242,ZRET,ZRET,20,3650,007907269 / 400055387 / MICROESFERA VIDR,NaN,1,2022-07-18
23,1917244,ZRET,ZRET,20,3650,007907269 / 400055389 / MICROESFERA VIDR,NaN,1,2022-07-18
24,1908426,ZRET,ZRET,20,3650,007907269 / RI400054633 / MICROESFERA,NaN,1,2022-05-10

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66505 entries, 0 to 66504
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Ordem                 66505 non-null  int64
 1   Tipo de ordem first   66505 non-null  object
 2   Tipo de ordem         66505 non-null  object
 3   Operação              66505 non-null  int64
 4   Centro de trabalho    66505 non-null  object
 5   Texto breve material  66505 non-null  object
 6   Nº peça fabricante    59133 non-null  object
 7   Quantidade operação   66505 non-null  int64
 8   Fim real operação     66505 non-null  datetime64[ns]
 9   Nova Coluna           3441 non-null   object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 5.1+ MB

In [63]:
# Selecione as linhas da coluna que começam com um número
linhas_selecionadas = df[df['Texto breve material'].str.match('^\d')]
df.head(50)

,Ordem,Tipo de ordem first,Tipo de ordem,Operação,Centro de trabalho,Texto breve material,Nº peça fabricante,Quantidade operação,Fim real operação
0,1792311,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
1,1792311,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
2,1792311,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
3,1792312,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
4,1792312,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
5,1792312,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
6,1792313,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26
7,1792313,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26
8,1792313,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28
9,1904892,ZSER,ZSER,60,3508,-,NaN,8,2022-05-13
10,1920777,ZSER,ZSER,70,3508,-,NaN,1,2022-08-17
11,1925389,ZSER,ZSER,70,3508,-,NaN,1,2022-09-19
12,1934730,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
13,1934731,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
14,1934733,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
15,1934734,ZREC,ZREC,50,0586,-,NaN,1,2022-12-16
16,1939467,ZSER,ZSER,60,3508,-,NaN,12,2023-02-13
17,1910685,ZRET,ZRET,20,3650,007907269 / 400054806 / MICROESFERAVIDRO,NaN,1,2022-05-30
18,1910686,ZRET,ZRET,20,3650,007907269 / 400054807 / MICROESFERAVIDRO,NaN,1,2022-05-30
19,1910687,ZRET,ZRET,20,3650,007907269 / 400054808 / MICROESFERAVIDRO,NaN,1,2022-05-30
20,1912785,ZRET,ZRET,20,3650,007907269 / 400055003 / MICROESFERAVIDRO,NaN,1,2022-06-15
21,1912786,ZRET,ZRET,20,3650,007907269 / 400055004 / MICROESFERAVIDRO,NaN,1,2022-06-15
22,1917242,ZRET,ZRET,20,3650,007907269 / 400055387 / MICROESFERA VIDR,NaN,1,2022-07-18
23,1917244,ZRET,ZRET,20,3650,007907269 / 400055389 / MICROESFERA VIDR,NaN,1,2022-07-18
24,1908426,ZRET,ZRET,20,3650,007907269 / RI400054633 / MICROESFERA,NaN,1,2022-05-10
25,1909364,ZRET,ZRET,20,3650,007907269 / RI400054693 / MICROESFERA,NaN,1,2022-05-17
26,1909365,ZRET,ZRET,20,3650,007907269 / RI400054694 / MICROESFERA,NaN,1,2022-05-17
27,1921506,ZRET,ZRET,20,3650,007907269/ 400055960 /MICROESFERA VIDRO,NaN,1,2022-08-23
28,1921508,ZRET,ZRET,20,3650,007907269/ 400055961 /MICROESFERA VIDRO,NaN,1,2022-08-23
29,1903190,ZRET,ZRET,20,3650,007907269/RI400053831/MICROESFERA VIDR,NaN,1,2022-04-04
30,1903188,ZRET,ZRET,20,3650,007907269/RI400053832/MICROESFERA VIDR,NaN,1,2022-04-04
31,1904855,ZRET,ZRET,20,3650,007907269/RI400054345/MICROESFERA VIDR,NaN,1,2022-04-14
32,1905663,ZRET,ZRET,20,3650,007907269/RI400054414/MICROESFERA VIDRO,NaN,1,2022-04-26
33,1905664,ZRET,ZRET,20,3650,007907269/RI400054415/MICROESFERA VIDRO,NaN,1,2022-04-26
34,1906549,ZRET,ZRET,20,3650,007907269/RI400054485/MICROESFERA VIDRO,NaN,1,2022-04-28
35,1914349,ZRET,ZRET,20,3660,007907269/RI400055114/MICROESFERA VIDRO,NaN,1,2022-06-29
36,1914350,ZRET,ZRET,20,3660,007907269/RI400055115/MICROESFERA VIDRO,NaN,1,2022-07-01
37,1910530,ZRET,ZRET,40,0575,"009080247 / 200133375 / VERNIZ, POLIURET",NaN,1,2022-06-01
38,1910530,ZRET,ZRET,50,0586,"009080247 / 200133375 / VERNIZ, POLIURET",NaN,1,2022-06-03
39,1908399,ZRET,ZRET,40,0586,010021066 / 200133367 / TINTA PTFE - XYL,NaN,1,2022-05-12
40,1921038,ZRET,ZRET,40,0586,010025224/ 200134991 /RESINA ACRILICA PR,NaN,1,2022-08-19
41,1903195,ZRET,ZRET,40,0586,010040141/QM200132641/PRIMER EPOXI VERDE,NaN,1,2022-04-08
42,1930852,ZRET,ZRET,40,0586,010040141/QM200136686/PRIMER EPOXI VERDE,NaN,1,2023-01-23
43,1908575,ZRET,ZRET,40,0586,"010054563 / 200132911 / LUBRIFICANTE, FI",NaN,1,2022-05-16
44,1935382,ZRET,ZRET,40,0586,"010054563/QM200137537/LUBRIFICANTE, FILM",NaN,1,2022-12-06
45,1928708,ZRET,ZRET,30,3401,010054909/QM200136114/VERNIZ PARA MASCAR,NaN,1,2023-02-23
46,1923671,ZRET,ZRET,40,0575,"010067416/QM200135573/TINTA,POLIURETANO,",NaN,1,2022-09-06
47,1923671,ZRET,ZRET,80,0586,"010067416/QM200135573/TINTA,POLIURETANO,",NaN,1,2022-09-09
48,1923671,ZRET,ZRET,90,0586,"010067416/QM200135573/TINTA,POLIURETANO,",NaN,1,2022-09-09
49,1909772,ZRET,ZRET,40,0575,010069928 / 200133139 / TINTA PU AMARELA,NaN,1,2022-05-31

In [82]:
import re

padrao = r".*?(?=/)"
df["Selecionado"] = df["Texto breve material"].apply(lambda x: re.findall(padrao, x)[0] if re.findall(padrao, x) else None)

# Selecione os números até o caractere '/'
#numeros_selecionados = linhas_selecionadas['Texto breve material'].str.extract('^(\d+)', expand=False)

In [83]:
# Adicione uma nova coluna ao DataFrame com os números selecionados
df['Nova Coluna'] = numeros_selecionados
df.head(2000)

,Ordem,Tipo de ordem first,Tipo de ordem,Operação,Centro de trabalho,Texto breve material,Nº peça fabricante,Quantidade operação,Fim real operação,Nova Coluna,Selecionado
0,1792311,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26,NaN,None
1,1792311,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26,NaN,None
2,1792311,ZSER,ZSER,90,3500,-,NaN,1,2022-09-28,NaN,None
3,1792312,ZSER,ZSER,60,0571PM,-,NaN,1,2022-09-26,NaN,None
4,1792312,ZSER,ZSER,70,0583,-,NaN,1,2022-09-26,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
1995,1909359,ZRET,ZRET,140,0571PM,"196-60456-005 / 200133236 / EIXO CARDAN,",NaN,1,2022-06-08,NaN,196-60456-005
1996,1909359,ZRET,ZRET,160,0583,"196-60456-005 / 200133236 / EIXO CARDAN,",NaN,1,2022-06-09,NaN,196-60456-005
1997,1909359,ZRET,ZRET,180,0586,"196-60456-005 / 200133236 / EIXO CARDAN,",NaN,1,2022-06-09,NaN,196-60456-005
1998,1912619,ZRET,ZRET,10,3401,196-60460-001 / 200134080 / PARAFUSO - H,NaN,6,2022-06-14,NaN,196-60460-001
1999,1912619,ZRET,ZRET,30,3610,196-60460-001 / 200134080 / PARAFUSO - H,NaN,6,2022-06-15,NaN,196-60460-001